### ISSUE TITLE
vectorising dirty2vis over frequency

### ISSUE THREAD

**Issue by Joshuaalbert** [mreineck/ducc#41]
A common task is predicting visibilities at many frequencies, sometimes with one image per channel (`image: [num_l, num_m, chan], freq: [chan] -> vis: [row, chan]`), but also sometimes from a single image but at multiple different frequencies (`image: [num_l, num_m], freq: [chan] -> vis: [row, chan]`). Would it be possible to incorperate this functionality into wgridder, and would it be faster than simply calling `dirty2vis` sequentially on each channel? And, ideally it performs well when brought into JAX, either through `jax.pure_callback` or jaxBind.

**Comment by mreineck** [comment]
I'm pretty sure that there is not much performance to be gained by a custom implementation vs. calling `dirty2vis` in a loop over channels. However, when calling `dirty2vis` separately for every channel, it might be helpful to reorganize the `vis` array on the user side, such that the `row` dinension is the fastest growing index, i.e. that te entries for `[chan,row]` and `[chan,row+1]` are adjacent in memory.
Performance should not change at all if the code is called through JAX, since exactly the same code will be executed as before; there is no compilation or translation of any sort going on.

**Comment by Joshuaalbert** [comment]
Thanks! That's more or less what I expected. I'm thinking then to use a thread pool to do `(image: [num_l, num_m, chan], freq: [chan] -> vis: [row, chan])`, with a `nthreads=1` per `dirty2vis` invokation. Does that sound reasonable? Also, per your advice making sure that memory is in Fortran ordering, or column major so that memory changes quickest over `row`. I suppose for the `image` it makes sense that it should be over `l` then `m` then `chan` (if not please specify)?

**Comment by mreineck** [comment]
The parallelization approach sounds good; if you only have the `dirty2vis` call in the parallel region, it should work well, because the GIL is released while executing the C++ code.
Concerning memory arrangement: the only important guideline is that memory areas accessed by different `dirty2vis` invocations are not interleaved. So if you have an outer loop over `chan`, then probably `chan` should be changed from fastest moving index to slowest moving index.

**Comment by Joshuaalbert** [comment]
Thanks! I'll close this then.
